services:
  postgres:
    container_name: postgres-sql-uitbn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: uit_book_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-uitbn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  uitbn-api:
    container_name: uitbn-api
    image: uitbn/uitbn:1.0.0
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local