spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uit_book_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: tnty2608@gmail.com
    password: skvn tqol qyjo uwsg
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true
    protocol: smtp

application:
  security:
    jwt:
      secret-key: D225FA492A925C1FA15DDB43B41BC48935BB93284D8A6459ED9E6D8AE7
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      photos-output-path: ./uploads

server:
  port: 8088